version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - app-db
    networks:
      - app-network
    env_file:
      - .env
    
  app-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: docker-fastapi-app-db
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      TEST_DATABASE_NAME: ${TEST_DATABASE_NAME}
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${Y}
      MSSQL_PID: ${MSSQL_PID}
      SQL_SERVER: ${SQL_SERVER}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - app-network

  app-test:
    build:
      context: .
      dockerfile: expensemgr/docker/application-testing/Dockerfile
    depends_on:
      - app-db
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=${TESTDB_URL}

networks:
 app-network:
   driver: bridge